version: "3.9"

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "pulse"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"